name: PR checks

on: pull_request

jobs:
  cancel-previous:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  helm-check:
    runs-on: ubuntu-latest
    needs: [cancel-previous]
    steps:
    - uses: actions/checkout@master
    - name: helm-check
      uses: igabaydulin/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./
        CHART_VALUES: ./values.yaml

# This is to check what will be the next version for release and changelog content
  dry-run-release:
    name: dry-run release
    runs-on: ubuntu-latest
    needs: [cancel-previous]
    steps:
      - name: (Dry-run) Bump version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          custom_release_rules: major:major:Major Changes,minor:minor:Minor Changes,chore:patch:Chores
          dry_run: true